services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - 80:80
    volumes:
      - ./html/index.html:/usr/share/nginx/html/index.html
    restart: always
  filebrowser:
    container_name: filebrowser
    image: hurlenko/filebrowser
    user: "${PUID}:${PGID}"
    ports:
      - 8080:8080
    volumes:
      - ${MEDIA_DIRECTORY}:/data
      - ${INSTALL_DIRECTORY}/config/filebrowser:/config
    environment:
      - FB_BASEURL=/
    restart: always
